// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRecord = "record"

// Record mapped from table <record>
type Record struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	InstanceID int64          `gorm:"column:instance_id;not null" json:"instance_id"`
	Domain     string         `gorm:"column:domain;not null" json:"domain"`
	Target     string         `gorm:"column:target;not null" json:"target"`
	Port       int32          `gorm:"column:port" json:"port"`
	CreatedAt  time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Record's table name
func (*Record) TableName() string {
	return TableNameRecord
}
